require: rubocop-performance

################ General configuration ###################
AllCops:
  TargetRubyVersion: 2.4
  DisplayStyleGuide: true
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/structure.sql"
    - "db/seeds.rb"
    - ".bundle/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"

################ Disable cops ############################
Documentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Security/Open:
  Enabled: false

################ Enable cops #############################
Rails:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/Send:
  Enabled: true

################ Customize cops ##########################
Style/AndOr:
  EnforcedStyle: conditionals

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/SignalException:
  EnforcedStyle: semantic

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%": "()"
    "%i": "()"
    "%q": "()"
    "%Q": "()"
    "%r": "{}"
    "%s": "()"
    "%w": "[]"
    "%W": "[]"
    "%x": "()"

Style/DateTime:
  Exclude:
    - "spec/**/*"

Rails/TimeZone:
  Exclude:
    - "spec/**/*"

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Metrics/LineLength:
  Max: 90
  Exclude:
    - spec/**/*
    - "db/migrate/**/*"

Metrics/AbcSize:
  Max: 22
  Exclude:
    - "db/migrate/**/*"

Metrics/MethodLength:
  Max: 12
  Exclude:
    - "db/migrate/**/*"
    - "lib/tasks/**/*"
    - "spec/**/*"

Metrics/ClassLength:
  Max: 150
  Exclude:
    - "db/migrate/**/*"

Metrics/ModuleLength:
  Max: 150

Naming/VariableNumber:
  EnforcedStyle: "snake_case"

# ActiveAdmin, some config files (like rails environments or simple form) and the Rspec
# specs use large blocks that we shouldn't consider as problems.
Metrics/BlockLength:
  Exclude:
    - "app/admin/**/*"
    - "config/**/*"
    - "spec/**/*"
    - "lib/tasks/**/*"
Style/LambdaCall:
  Exclude:
    - "**/*.jbuilder"
