default: &default
  adapter: postgresql
  host: postgres
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: atpls-share-development

test:
  <<: *default
  database: atpls-share-test

production:
  url: <%= ENV['DATABASE_URL'] %>
